"""Capture the evidence the demo page renders. Nothing on that page is written by hand.

    python3 -m examples.demo_capture --out docs/demo/evidence.json

Three kinds of capture, labelled as such in the output because they are not
equally strong:

* `live`      - real traffic over the public relay, using only open operations.
* `local`     - a relay, a worker and a demonstration issuer started here, so
                the gated exchanges are reproducible by anyone running this file.
* `computed`  - results calculated directly against a database on this machine,
                for data this town does not serve over the relay.

Local filesystem paths are stripped from the output, since the file is published.

The demonstration issuer's public key is published in the output so a reader can
verify every signature in the transcript for themselves.
"""

import argparse
import base64
import json
import secrets
import sqlite3
import sys
import tempfile
import threading
from datetime import datetime, timezone
from http.server import ThreadingHTTPServer
from pathlib import Path

from wasteland.client import Client, Worker, join
from wasteland.hub import Store, handler
from wasteland.protocol import canonical

from . import agreement as undertaking
from . import credential_status, ed25519, mimic_fixture, mimic_handler, mimic_load
from . import mimic_budget, mimic_presentation as presentation
from . import mimic_service as service

ISSUER = "https://w3id.org/academic-wasteland/demo/issuers/demonstration"
SUBJECT = "urn:participant:demo-researcher"
b64 = lambda raw: base64.urlsafe_b64encode(raw).decode().rstrip("=")


def _sign(document, secret, issuer=ISSUER):
    body = {k: v for k, v in document.items() if k != "proof"}
    return {**body, "proof": {
        "type": presentation.PROOF_TYPE,
        "verificationMethod": issuer + "#key-1",
        "proofValue": b64(ed25519.sign(secret, canonical(body).encode()))}}


def _credential(issuer_secret, holder_secret, roles=("DemonstrationRequester",)):
    key = "ed25519:" + b64(ed25519.public_key(holder_secret))
    return _sign({
        "@context": ["https://www.w3.org/ns/credentials/v2"],
        "id": "https://w3id.org/academic-wasteland/demo/credentials/demo-1",
        "type": ["VerifiableCredential", "Qualification"],
        "issuer": ISSUER,
        "validFrom": "2026-09-01T00:00:00Z",
        "credentialSubject": {"id": SUBJECT, "roles": list(roles),
                              "holderKey": key, "publicKey": key},
        "credentialStatus": {
            "id": "https://w3id.org/academic-wasteland/demo/status/demo-1",
            "type": "RegistrarStatus"},
    }, issuer_secret)


def live(town="zerzura", state=".town-client"):
    """Open operations against the public relay, sent by a separate town."""
    client = Client(state)
    out = {}
    for operation in ("describe", "mimic-schema", "mimic-agreement"):
        message_id = client.ask(town, operation=operation,
                                body={"operation": operation})
        reply = client.wait(message_id, 90)[-1]
        out[operation] = {"request_id": message_id, "reply_id": reply["id"],
                          "created": reply["created"], "body": reply["body"]}
    return out


class _Local:
    """A relay, a Zerzura worker and a requester town, all started here."""

    def __init__(self, root, dataset, issuer_secret):
        self.root = root
        trust = {"fetched": datetime.now(timezone.utc).isoformat(),
                 "source": "demonstration issuer, generated by demo_capture.py",
                 "issuers": [{"id": ISSUER,
                              "publicKey": "ed25519:" + b64(ed25519.public_key(issuer_secret)),
                              "accreditations": []}]}
        (root / "trust.json").write_text(json.dumps(trust, indent=2))
        import os
        os.environ.update({
            "WASTELAND_MIMIC_DB": str(dataset),
            "WASTELAND_CAMELOT_TRUST": str(root / "trust.json"),
            "WASTELAND_CAMELOT_ROOT_ISSUERS": ISSUER,
            "WASTELAND_MIMIC_TRUSTED_ISSUERS": ISSUER.rsplit("/", 1)[0] + "/",
            "WASTELAND_MIMIC_CHALLENGES": str(root / "c.sqlite"),
            "WASTELAND_MIMIC_ASSENT": str(root / "s.sqlite"),
            "WASTELAND_MIMIC_AUDIT": str(root / "a.sqlite"),
            "WASTELAND_MIMIC_LEDGER": str(root / "l.sqlite"),
        })
        self.store = Store(root / "hub.sqlite")
        invite = secrets.token_urlsafe(32)
        self.server = ThreadingHTTPServer(("127.0.0.1", 0),
                                          handler(self.store, invite, "http://127.0.0.1"))
        threading.Thread(target=self.server.serve_forever, daemon=True).start()
        base = "http://127.0.0.1:" + str(self.server.server_port)
        join(root / "zerzura", base, "zerzura", invite, "Zerzura")
        join(root / "peer", base, "demo_requester", invite, "Demo requester")
        self.worker = Worker(root / "zerzura", mimic_handler.handle)
        self.client = Client(root / "peer")

    def exchange(self, body):
        message_id = self.client.ask("zerzura", operation=body["operation"], body=body)
        self.worker.tick()
        reply = self.client.wait(message_id, 15)[-1]
        return {"request": body, "request_id": message_id, "reply": reply["body"]}

    def close(self):
        self.server.shutdown()
        self.server.server_close()


def gated(root, dataset, issuer_secret, holder_secret):
    """Every way a request is refused, and the one way it succeeds."""
    local = _Local(root, dataset, issuer_secret)
    credential = _credential(issuer_secret, holder_secret)
    thief_secret = bytes(range(80, 112))
    query = {"cohort": [{"field": "admission_type", "op": "eq", "value": "EW EMER."}],
             "aggregate": "mortality_rate", "group_by": ["age_group"]}
    steps = []

    def challenge():
        return local.exchange({"operation": "mimic-challenge"})["reply"]["challenge"]

    def present(secret, q=query, challenge_value=None):
        created = datetime.now(timezone.utc).isoformat()
        value = challenge_value or challenge()
        message = presentation.binding(
            challenge=value, created=created, credential_id=credential["id"],
            query=q, subject=SUBJECT, town="zerzura")
        return {"type": presentation.PROOF_TYPE, "challenge": value, "created": created,
                "proofValue": b64(ed25519.sign(secret, message))}

    def step(title, explain, body):
        result = local.exchange(body)
        steps.append({"title": title, "explains": explain, **result})
        return result

    step("No credential at all",
         "The gate is not optional, and the refusal names what is missing.",
         {"operation": "mimic-aggregate", "query": query})

    forged = json.loads(json.dumps(credential))
    forged["credentialSubject"]["roles"] = ["Administrator"]
    step("A credential altered after signing",
         "One field changed breaks the issuer's signature over the whole document.",
         {"operation": "mimic-aggregate", "credential": forged, "query": query,
          "presentation": present(holder_secret)})

    step("A genuine credential, presented by someone without the key",
         "This is the case a signature alone cannot catch: the document is real, "
         "the presenter is not its subject.",
         {"operation": "mimic-aggregate", "credential": credential, "query": query,
          "presentation": present(thief_secret)})

    step("Everything valid, but no undertaking given",
         "Verifying who is asking does not settle what they have agreed to.",
         {"operation": "mimic-aggregate", "credential": credential, "query": query,
          "presentation": present(holder_secret)})

    current = undertaking.agreement()
    created = datetime.now(timezone.utc).isoformat()
    assent_message = undertaking.binding(digest=current["digest"], version=current["version"],
                                         subject=SUBJECT, town="zerzura", created=created)
    step("Giving the undertaking",
         "Signed with the same key the credential names. What is stored is a digest, "
         "a version, a subject, a signature and a time - no document belonging to anyone else.",
         {"operation": "dua-assent", "credential": credential,
          "assent": {"agreement": current["digest"], "version": current["version"],
                     "created": created,
                     "proofValue": b64(ed25519.sign(holder_secret, assent_message))}})

    spent = present(holder_secret)
    answered = step("The same query, now answered",
                    "Credential verified, holder proven, undertaking on file.",
                    {"operation": "mimic-aggregate", "credential": credential, "query": query,
                     "presentation": spent})

    step("That exact presentation, replayed",
         "Challenges are single use, so a captured presentation is worth nothing twice.",
         {"operation": "mimic-aggregate", "credential": credential, "query": query,
          "presentation": spent})

    narrowed = dict(query, group_by=["age_group", "insurance"])
    step("A captured presentation, re-aimed at a different question",
         "The holder's signature covers a digest of the exact query, so the proof "
         "does not transfer to another one.",
         {"operation": "mimic-aggregate", "credential": credential, "query": narrowed,
          "presentation": present(holder_secret, q=query)})

    local.close()
    return {"steps": steps, "agreement": current, "answered": answered["reply"]}


def policy_contrast(root):
    """The same rows under two policies: identical query, different answers."""
    mimic_load.build(mimic_load.BUNDLED, root / "public.sqlite",
                     mimic_load.descriptor(mimic_load.BUNDLED))
    mimic_load.build(mimic_load.BUNDLED, root / "controlled.sqlite",
                     mimic_load.descriptor(root, name="mimic-iv-demo-as-controlled",
                                           description="The same rows, not declared public."))
    query = {"aggregate": "count", "group_by": ["care_unit"]}
    out = {"query": query, "datasets": {}}
    for label, name in (("public", "public.sqlite"), ("controlled", "controlled.sqlite")):
        result = service.run(query, root / name)
        out["datasets"][label] = {
            "policy": service.policy(root / name),
            "dataset": service.dataset(root / name),
            "result": result,
        }
    return out


def differencing(database):
    """Two legal questions whose difference describes a handful of people."""
    root = Path(tempfile.mkdtemp())
    import os
    os.environ["WASTELAND_MIMIC_LEDGER"] = str(root / "ledger.sqlite")
    ledger = mimic_budget.CohortLedger()
    cohort = [{"field": "gender", "op": "eq", "value": "F"},
              {"field": "admission_type", "op": "eq", "value": "ELECTIVE"}]
    where = (" WHERE p.gender='F' AND a.admission_type='ELECTIVE'")
    connection = sqlite3.connect(f"file:{database}?mode=ro", uri=True)

    # Find any dimension holding a category too small to release, few enough that
    # the remaining values fit inside one filter.
    chosen = None
    for dimension, expression in service.DIMENSIONS.items():
        rows = connection.execute(
            f"SELECT {expression}, COUNT(*) FROM icustays s"
            " JOIN admissions a ON a.hadm_id = s.hadm_id"
            " JOIN patients p ON p.subject_id = s.subject_id"
            + where + f" GROUP BY {expression}").fetchall()
        present = [(value, count) for value, count in rows if value is not None]
        if len(present) - 1 > service.MAX_IN_VALUES:
            continue
        below = [(value, count) for value, count in present
                 if 0 < count < service.MIN_CELL]
        if below:
            chosen = (dimension, min(below, key=lambda pair: pair[1]),
                      [value for value, _ in present])
            break
    if chosen is None:
        return None
    dimension, (target, hidden), values = chosen
    keep = [value for value in values if value != target]

    first, members = service.run({"cohort": cohort, "aggregate": "count"},
                                 database, with_membership=True)
    ledger.check_differencing("demo", mimic_budget.membership_sets(first, members))
    ledger.record("demo", mimic_budget.membership_sets(first, members))
    second, members = service.run(
        {"cohort": cohort + [{"field": dimension, "op": "in", "value": keep}],
         "aggregate": "count"}, database, with_membership=True)
    try:
        ledger.check_differencing("demo", mimic_budget.membership_sets(second, members))
        refusal = None
    except mimic_budget.BudgetError as error:
        refusal = str(error)
    ledger.close()
    return {
        "dimension": dimension,
        "hidden_category": target,
        "hidden_size": hidden,
        "minimum_cell_size": service.MIN_CELL,
        "first": {"query": first["query"], "cohort_size": first["cohort_size"]},
        "second": {"query": second["query"], "cohort_size": second["cohort_size"]},
        "difference": first["cohort_size"] - second["cohort_size"],
        "refusal": refusal,
    }


def comparison(demo, controlled):
    """The same questions against the extract we serve and the database we do not.

    Two things differ at once and both matter: the controlled database is three
    orders of magnitude larger, and because it declares nothing it receives full
    disclosure control while the openly licensed extract receives none.
    """
    queries = [
        {"title": "ICU stays by care unit",
         "query": {"aggregate": "count", "group_by": ["care_unit"]}},
        {"title": "In-hospital mortality by admission type",
         "query": {"aggregate": "mortality_rate", "group_by": ["admission_type"]}},
    ]
    out = []
    for entry in queries:
        row = {"title": entry["title"], "query": entry["query"], "sides": {}}
        for label, database in (("demo", demo), ("controlled", controlled)):
            result = service.run(entry["query"], database)
            row["sides"][label] = {
                "dataset": service.dataset(database),
                "policy": service.policy(database),
                "result": result,
                "withheld": sum(1 for g in result["groups"] if "suppressed" in g),
            }
        out.append(row)
    return out


def headline(database):
    """Results worth looking at, so the page is about something."""
    out = {"dataset": service.dataset(database), "queries": []}
    for title, query in (
        ("In-hospital mortality by admission type",
         {"aggregate": "mortality_rate", "group_by": ["admission_type"]}),
        ("Mean ICU length of stay by age group",
         {"aggregate": "mean", "measure": "los_days", "group_by": ["age_group"]}),
    ):
        result = service.run(query, database)
        out["queries"].append({"title": title, **result})
    return out


def redact(node):
    """Strip anything that describes this machine. The output file is published."""
    if isinstance(node, dict):
        return {key: redact(value) for key, value in node.items()}
    if isinstance(node, list):
        return [redact(value) for value in node]
    if isinstance(node, str) and (node.startswith("/") or node.startswith("~")) \
            and "/" in node.lstrip("/"):
        return "(local path withheld)"
    return node


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("docs/demo/evidence.json"))
    parser.add_argument("--real", type=Path,
                        default=Path.home() / "mimic-iv" / "mimic-iv.sqlite",
                        help="a controlled database, used for computed captures only")
    parser.add_argument("--skip-live", action="store_true")
    parser.add_argument("--live-state", default=".town-client",
                        help="state directory of the town that sends the live captures")
    args = parser.parse_args()

    root = Path(tempfile.mkdtemp())
    issuer_secret, holder_secret = bytes(range(32)), bytes(range(32, 64))
    dataset = root / "demo.sqlite"
    mimic_load.build(mimic_load.BUNDLED, dataset, mimic_load.descriptor(mimic_load.BUNDLED))

    evidence = {
        "captured": datetime.now(timezone.utc).isoformat(),
        "demonstration_issuer": {
            "id": ISSUER,
            "publicKey": "ed25519:" + b64(ed25519.public_key(issuer_secret)),
            "note": "Generated by this script so every signature below can be checked. "
                    "It is not accredited by anyone and no town trusts it by default.",
        },
        "gated": gated(root, dataset, issuer_secret, holder_secret),
        "policy_contrast": policy_contrast(root),
    }
    if not args.skip_live:
        try:
            evidence["live"] = live(state=args.live_state)
        except Exception as error:  # noqa: BLE001 - the relay may simply be unreachable
            evidence["live_error"] = f"{type(error).__name__}: {error}"
    if args.real.exists():
        # The path itself is deliberately not recorded: this file is published.
        evidence["real"] = {"headline": headline(args.real),
                            "differencing": differencing(args.real),
                            "comparison": comparison(dataset, args.real)}
    args.out.parent.mkdir(parents=True, exist_ok=True)
    evidence = redact(evidence)
    args.out.write_text(json.dumps(evidence, indent=2, sort_keys=True))
    print(f"wrote {args.out} ({args.out.stat().st_size/1024:.0f} KB)")
    print("  gated steps   :", len(evidence["gated"]["steps"]))
    print("  live captures :", len(evidence.get("live", {})))
    print("  real data     :", "yes" if "real" in evidence else "not present")


if __name__ == "__main__":
    main()
